// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cell } from './Cell';
import type { GeneticParams } from './GeneticParams';
import type { Player } from './Player';

export interface GameState {
  board: Array<Array<Cell>>;
  current_player: Player;
  genetic_params: GeneticParams;
}
