// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GeneticParams {
  id: string;
  parent_ids: Array<string>;
  generation: number;
  win_score: number;
  loss_score: number;
  center_column_value: number;
  adjacent_center_value: number;
  outer_column_value: number;
  edge_column_value: number;
  row_height_weight: number;
  center_control_weight: number;
  piece_count_weight: number;
  threat_weight: number;
  mobility_weight: number;
  vertical_control_weight: number;
  horizontal_control_weight: number;
  defensive_weight: number;
}
