// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MLMoveEvaluation } from './MLMoveEvaluation';

export interface MLDiagnostics {
  validMoves: Array<number>;
  moveEvaluations: Array<MLMoveEvaluation>;
  valueNetworkOutput: number;
  policyNetworkOutputs: Array<number>;
}
