// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoveEvaluationWasm } from './MoveEvaluationWasm';

export interface WasmBestMoveResponse {
  move: number | null;
  evaluations: Array<MoveEvaluationWasm>;
  nodesEvaluated: number;
  transpositionHits: number;
}
